### PR TITLE
Store key expiry date and flag a warning

### PR DESCRIPTION
**Pull request by jitendrapurohit**
Flagging as wip till it is tested on any one site.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
This is a good idea. A couple of thoughts

1) it looks like you have run civix over the code & have some civix updates with no functional change. It's probably worth doing that as a fix first & getting it merged (you might need to re-do those steps to make the changes over a clean version of the repo). 

2) It seems like a system check to warn, say 2 weeks before, would be useful

**Comment by jitendrapurohit** [comment]
Updated this to only display a warning on system status page instead of saving expiry key into DB and showing it on xero settings page.

**Comment by eileenmcnaughton** [comment]
Hey - make sure you remove wip from the title when you think this is done, am ignoring the notifications as long as I see 'wip'

**Comment by jitendrapurohit** [comment]
Sure, Gemma will test on one site and would remove the tag as soon as I get a positive response. Thanks.

**Comment by petednz** [comment]
as per redmine ticket. can this show the expiry date at /civicrm/xero/settings or on System Status so there is proof this feature is on the site? Then trigger the alert when x days remaining?

**Comment by jitendrapurohit** [comment]
just removed the wip from the title. It has been tested on one site.

**Pull request merged**
