### PR TITLE
Exposing the account sync error logs in the CiviCRM UI

### PR DESCRIPTION
**Pull request by agilewarealok**
Exposing the Account Sync error logs in the CiviCRM UI so that error messages in civicrm_account_contact and civicrm_account_invoice can be reviewed.

## Implementation
1. Showing (?) icon on view contact page clicking on it opens CiviCRM error popup which displays the error message.
2. Displaying all the errors on single page, we have created two new pages under Xero menu which shows all error logs from Contacts and Invoices table.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit @petednz  you might be interested in this

@agilewarealok in general I'm pretty happy to merge this based on very little review / QA since it only adds a feature. My one reservation is around the permissions - since this is open to 'Access CiviCRM' it might expose personal or contribution related data to someone who would not otherwise have permissions to view it

**Comment by agilewarealok** [comment]
@eileenmcnaughton 
We've updated the access to `access CiviContribute`.

**Comment by eileenmcnaughton** [comment]
@jitendrapurohit @petednz I don't have much skin in the permissions side of this but you might wish to weigh in on whether you think it needs more protection than access Contribute. this PR basically exposes the civicrm account sync tables (which hold name & address data for donors generally)

**Comment by jitendrapurohit** [comment]
+1 for the fix/improvement. will check with @petednz about the permission. For me, I think the `access CiviContribute` is ok for now.

**Comment by eileenmcnaughton** [comment]
Hmm - I think I'd prefer to add a special permission now I think about it - I just worry that an acl using site might assume that it's safe but actually it might not be & 'opting in' with a permission seems safest

**Comment by agilewarealok** [comment]
Closing this as it has been merged via another PR #40

**Pull request closed without merging**
