### PR TITLE
Revert "Partial switch to Guzzle"

### PR DESCRIPTION
**Pull request by mattwire**
This reverts commit 9a9cbafcfb90dfae184df82eca434e218b1e5848.

Per #107 this completely breaks Xero for me so I think best to revert for now.

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
@mattwire did you have a go at the other library you suggested? I'm happy to revert to put in a different library but I'm really really worried about the lack of tests & this was part of starting to add that - so I think we need to make sure there is a clear plan for test cover before doing much more

**Comment by mattwire** [comment]
@eileenmcnaughton I only got as far as looking at it. It would be quite a bit of work to integrate but would be much easier to maintain / support once done. It handles all the oauth stuff as well as the data.

The reason for revert is because the changes in that commit break communication with Xero for me.

**Comment by eileenmcnaughton** [comment]
@mattwire yeah - but I think it's an easy change to switch from POST to GET and I think getting testing on the sync functions is a priority before we start changing the inner logic in them (which I know is in your list after we've worked through some of these more super-ficial display & menu changes)

**Comment by eileenmcnaughton** [comment]
@mattwire I took a look & fixing the things you spotted with Guzzle was pretty trivial. It seems to be working fine for me on master & this means we should be able to add unit tests with any changes to the push & pull api actions (I'm OK with not adding unit tests with any metadata based changes like adding searches, managed entities)

**Pull request closed without merging**
