### PR TITLE
OAuth2 authentication support for the extension

### PR DESCRIPTION
**Pull request by rajeshrhino**
- Implement Xero Authorization
- Add 3rd Party libraries
- Adapt Xero api classes to use OAuth
- Add status check for OAuth 2.0 settings
- Implement OAuth 2.0 Provider
- Refactor Authorization page
- Code formatting
- Update README with OAuth 2.0 connection steps

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
How does this work for  sites already   using OATH1 - will  that  still  work?

ping @agileware-fj @petednz @jitendrapurohit

**Comment by petednz** [comment]
We had a client whose synch had broken last week (not sure why) so we had to replace with parvez' version. i just swopped out the civixero code, then pasted the relevant url in to the Xero app setting, and then back in civi I clicked on 'authorise' and afaik all was good. will be getting @jitendra to review later but i didn't observe any issues

**Comment by eileenmcnaughton** [comment]
@petednz OK  so there ARE manual steps that need to be  taken  then  when a site switches

**Comment by petednz** [comment]
in terms of xero it is basically 'start again' and then in civi it is 'authorise'

**Comment by cmolava** [comment]
@eileenmcnaughton  just to confirm, this only implements OAuth 2.0. The OAuth 1.0 implementation is removed. 
When switching, site owners will need to create a new Xero App and reconfigure CiviXero, as @petednz  says. 

The README has more details on the steps.

Some of the differences for a site switching from 1.0 to 2.0:
-  Unlike a private app, the new Xero app isn't necessarily connected to the organisation. In practice, we'd expect the app to be created by an organisation owner but that will not by itself grant access to its resources.
- A user needs to perform an extra authorization step in Civi, using their Xero account credentials.
- SSL certificates are no longer required.
- The extension should connect within 30 days after the last connection, otherwise someone will need to authorize again. This shouldn't be an issue if the site has sync jobs scheduled.

These changes were unavoidable since the grant type implemented by Xero differs from the 2-legged workflow they had in place before. 

Another change is that multiple connections via Connectors haven't been implemented yet.

**Comment by eileenmcnaughton** [comment]
I still haven't found time to get my head around this :-(

But from what I can tell my best path at this stage is to merge this now & then it is in master. It won't 'hit' until I cut a release & I still need some release notes for then to inform people about the change - although I think @petednz suggested upgrading may not require immediate action from sites.

Regardless I think I need to be clear about that before I release but that merging now makes sense as it's clearly going to be merged & it is a big enough change that any fix ups should be post rather than pre merge!

**Comment by eileenmcnaughton** [comment]
Thanks to @rajeshrhino  - does Veda want to do any blog or anything announcing this valuable piece of work you have done?

**Comment by petednz** [comment]
>  I think @petednz suggested upgrading may not require immediate action from sites

correct. this is only an issue for new sites, or existing integrations which need to reestablish a connection eg if someone foolishly deleted a folder on server with the keys etc, or if the key has expired

**Pull request merged**
